document.addEventListener('DOMContentLoaded', () => {
    const searchForm = document.getElementById('membershipSearchForm');
    const searchInput = document.getElementById('membershipInput');
    const resultsContainer = document.getElementById('searchResultsContainer');
    const resultCountBox = document.getElementById('searchResultCount');
    const notFoundBox = document.getElementById('membershipNotFound');

// Dynamic session calculation helper based on GSTU/BSMRSTU batch codes
    const calculateSession = (clubId) => {
        if (!clubId) return '';
        const batchCode = clubId.substring(0, 2);
        switch (batchCode) {
            case '22':
            case '23':
            case '24':
                return '';
            default: return '';
        }
    };

    // Raw dataset with standardized academic faculties and departments
    const rawMembers = [
        // --- Batch 22SC (Session 2021-22) ---
        { clubId: "22SC001", name: "Riaz Munsi", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC002", name: "Md. Azizul Rahman", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC003", name: "Shakibul Alam", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC004", name: "Azizul Haque", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC005", name: "Md Aftab", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC006", name: "Ujjal Hira", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC007", name: "Miraz", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC008", name: "Abdul Shakib", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC009", name: "Wali Ahmed", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "22SC010", name: "M. M. Azmain Inkiad", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC011", name: "Nazmus Jubaer Nakib", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC012", name: "Md. Zaber Sadman", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC013", name: "Ashraful Islam Zihan", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine" },
        { clubId: "22SC014", name: "Mim Obydullah", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC015", name: "Alif Afridi", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC016", name: "KM Mamun Reza", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC017", name: "Shanto", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC018", name: "Rakibul Islam", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "22SC019", name: "Sharif Uddin Bahar", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "22SC020", name: "Zinnurain Mondol", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC021", name: "Nafisa Tabassum", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC022", name: "Papia Akter", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC023", name: "Fazlul Haque", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC024", name: "Jakaria Asif", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "22SC025", name: "Md. Ali Imran", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC026", name: "Sayed Taki", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC027", name: "Apon Mahammod", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC028", name: "Md. Hossain Ahmed", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC029", name: "Md. Sharif Islam", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC030", name: "Fahim Shahriar", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC031", name: "Md. Mostafizur Rahman", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC032", name: "Shoag Hossain", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "22SC033", name: "Delowar Hossain", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC034", name: "Md. Salahuddin", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "22SC035", name: "Md. Miraz", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "22SC036", name: "Md. Mehedi Hasan Shanto", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC037", name: "Jannatul Ferdous Ritu", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC038", name: "Masura Khatun", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC039", name: "Marzia Rahman Ahona", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC040", name: "Jannatul Ferdous", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC041", name: "Adindita Kabir", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC042", name: "Kaniz Fatema Shoily", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC043", name: "Arnob Mondal", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "22SC044", name: "Adiba Tasnim", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC045", name: "Tanjila Akter", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC046", name: "Farya Islam Mily", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "22SC047", name: "Nusrat Zahan", dept: "Statistics", faculty: "Faculty of Science" },
        { clubId: "22SC048", name: "Md Sabbir Hossen", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine" },
        { clubId: "22SC049", name: "Protikkha Mondal", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC050", name: "Shohana Akter", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC051", name: "Sadia Afrin", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC052", name: "Tasfiah Tasnim", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC053", name: "Rakib", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC054", name: "Saikat De", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC055", name: "Nurul Hasan Rahi", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC056", name: "Azizul Hakim", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC057", name: "Maria Sultana", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC058", name: "Moumita Islam Shishir", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC059", name: "Jannatul Ferdous Meem", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC060", name: "Nowreen Jahan Promee", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC061", name: "Md. Miraz Howlader", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC062", name: "Sajjad Hossain", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC063", name: "Rasel Mahamud", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC064", name: "Shoriful Islam", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC065", name: "Iftekhar Siddique", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC066", name: "Md. Jobeyer", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC067", name: "SK MD Hisbur Rahman", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC068", name: "Khandakar Mydul Islam", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC069", name: "CM Zarif Taa Seen", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC070", name: "Md. Luhanur Hossain Limon", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC071", name: "Nazmus Jubaer Nakib", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC072", name: "Al Amin", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC073", name: "Nighat Roudro", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC074", name: "Tanvir Alam Ovi", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC075", name: "Fahima Alamgir", dept: "Food Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC076", name: "Shuva", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "22SC077", name: "Md. Mashfiqur Rahman Niloy", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "22SC078", name: "Masura Khatun", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "22SC079", name: "Suma Begum", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC080", name: "Dipa", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "22SC081", name: "Arnob Mondal", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "22SC082", name: "Kazi Sanjida Alam", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "22SC083", name: "Tanjila Akter", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "22SC084", name: "Lubna Islam", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "22SC085", name: "Nabiha", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "22SC086", name: "Ambia Khatun", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC087", name: "Jarin Sultana Akhi", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "22SC088", name: "Dhurbo Chakrabarty", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "22SC089", name: "Maria Rahman", dept: "Psychology", faculty: "Faculty of Life Science" },

        // --- Batch 23SC (Session 2022-23) ---
        { clubId: "23SC001", name: "Md. Papul Mia", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC002", name: "Rasedul Islam", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC003", name: "Musfika Nazrin Mimi", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC004", name: "Asfaqur Rahman Ussho", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "23SC005", name: "SM Takrim Hasan", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC006", name: "Heaven Rupol Biswas", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC007", name: "Masura Khatun", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC008", name: "Akram Hossain Farhan", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC009", name: "Fuyad Al Mahdi", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC010", name: "Md. Mahir Farhan", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC011", name: "Md. Saiful Islam Bhuyan", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC012", name: "Md. Borhan Uddin Rabbni", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC013", name: "Md. Abdul Hasim Talukder", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC014", name: "Ishrat Jahan", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC015", name: "Md. Hridoy Munshi", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC016", name: "Ferdous Alom Fahim", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC017", name: "Shrabony Mondal Bristy", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC018", name: "Lamia Islam Ria", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC019", name: "Arif Billah Rume", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC020", name: "Joyjit Kunda Roy", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC021", name: "Adity Pandit Prantika", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC022", name: "Md. Nazrul Islam", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science" },
        { clubId: "23SC023", name: "Md. Barakat Ullah Miah", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC024", name: "Md. Shakil Hossain", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC025", name: "Most. Masuma Khatun", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC026", name: "Md. Jobayer", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC027", name: "Emon Das", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC028", name: "Md. Tamim Hasan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC029", name: "Anika Sharmila Arthy", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC030", name: "Md. Nayem Hossan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC031", name: "Md. Sohag", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "23SC032", name: "Md. Ripon", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC033", name: "Munshaya Tazria Hasan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC034", name: "Anika Anzum Maruya", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC035", name: "Dipa Bhattacharjee", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC036", name: "Md. Rafsan Islam", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "23SC037", name: "Ismita Tasnim Mim", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "23SC038", name: "Mst. Sadia Rahman", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC039", name: "Priya Dey", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC040", name: "Mahfuza Maliha", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC041", name: "Amrin Akter", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC042", name: "Sajida Shohid Oishe", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC043", name: "Jakiya Khanom", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC044", name: "Fariha Islam Toma", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC045", name: "Purabi Barai", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC046", name: "Md. Tanvir Hossain", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "23SC047", name: "Juma Akter", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "23SC048", name: "Ummey Habiba Hasu", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "23SC049", name: "Anika Rahman Nishi", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "23SC050", name: "Sakib Hossan Prottoy", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC051", name: "Shajjad Amir", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC052", name: "Raju Ahmed", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC053", name: "Imran Hossen", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC054", name: "Md. Imran Hossain", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC055", name: "Tanvir Ahmmed", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC056", name: "Raja Protap Roy", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC057", name: "Mafafuzor Rahman", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC058", name: "Kabir Hossain", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC059", name: "Tanvir Ahmed", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC060", name: "Md. Shafeyat Hossen", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC061", name: "Noyon Das", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC062", name: "Neamul Forkan", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC063", name: "Kawsar Anwar", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC064", name: "Ashikuzzaman Helal", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC065", name: "Toiyoba Tabassum Mim", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC066", name: "Asraful Sheikh", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC067", name: "Al-Fahim Sabbir", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC068", name: "Ishak Ali", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC069", name: "Fahim Hossen", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC070", name: "Afzal Hossen Kawar", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC071", name: "Tanjima Hafiz", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC072", name: "Afifa Khatun Bristy", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC073", name: "Jiniya Khatun", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC074", name: "Janntun Jami", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC075", name: "Parvez Ahmmed", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC076", name: "Swagata Mandol", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC077", name: "Md. Zubayer", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC078", name: "Farzana Akter Ema", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC079", name: "Monisha Bachar", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC080", name: "Farzana Yesmin", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC081", name: "Sadia Mehnaj Saila", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC082", name: "Afia Anjum Anisha", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC083", name: "Mitali Paul", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC084", name: "Fazley Rohan", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC085", name: "Sharmin Akter", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "23SC086", name: "Jarin Tasnim Aboni", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC087", name: "Md. Tawhidur Rahman", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC088", name: "Abhishek Mondol", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC089", name: "Rukaiya Afroz Rakhi", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC090", name: "Nadiatul Ferdaous Nadia", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC091", name: "Mojammel Khan Paris", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC092", name: "Sadman Ferdous Mugdha", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "23SC093", name: "Ariful Islam", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC094", name: "Md. Safi Al Sadit Chowdhury", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC095", name: "Md. Azim Uddin", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC096", name: "Md. Shazid Bin Hamid", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC097", name: "Debu Biswas", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC098", name: "Md. Jakir Hossain", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "23SC099", name: "Dipayan Rony", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC100", name: "Nurul Amin", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC101", name: "Shahin Alam", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC102", name: "Shadona Pramanik", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC103", name: "Bappa Ray", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC104", name: "Naziur Rahman", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC105", name: "Israt Jahan", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC106", name: "Shirin", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC107", name: "Nusrat", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC108", name: "Shairy", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC109", name: "Shamima", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC110", name: "Sumit", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC111", name: "Fauzia", dept: "Mathematics", faculty: "Faculty of Science" },
        { clubId: "23SC112", name: "Ashish Sutradhar", dept: "Physics", faculty: "Faculty of Science" },
        { clubId: "23SC113", name: "Nusrat Jahan Nisha", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC114", name: "Parvez Ahmed Chowdhury", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC115", name: "Md. Ashik Arif", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "23SC116", name: "Md. Shahabul Islam", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science" },
        { clubId: "23SC117", name: "Ela Akter", dept: "Psychology", faculty: "Faculty of Life Science" },
        { clubId: "23SC118", name: "S. M Al-Amin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "23SC119", name: "Rezoan Sharafat", dept: "Pharmacy", faculty: "Faculty of Life Science" },

        // --- Batch 24SC (Session 2023-24) ---
        { clubId: "24SC001", name: "Md. Al Amin Hossain", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC002", name: "Md. Shahed Hossin", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC003", name: "Shazzad Hosan Arif", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC004", name: "MD. Al Shaharia Bhuiyan", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC005", name: "Fattah Rahman Mahi", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC006", name: "Al Rabbi Mahid", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC007", name: "Md Shafin Sarkar", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC008", name: "Md Sabbir Hossen", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC009", name: "Md Ruman Mia", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC010", name: "Md Mashiur Rahman", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC011", name: "MD Riyad Biwas", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC012", name: "Farshid Ahmed Fahim", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC013", name: "Mahabuba Mustari Tanisha", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC014", name: "Zubayed Ibna Atique", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC015", name: "Manos Bhuiya", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC016", name: "Atoshi Islam Faria", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC017", name: "Rafsan Ahmmed Nabil", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC018", name: "Darathi Paul", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC019", name: "Md Rahul Hossen", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC020", name: "Suchana Fouzder Supty", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC021", name: "Tanzila Akter Putul", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC022", name: "Arpita Tabasum", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC023", name: "Tanvir Islam Uday", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC024", name: "Israt Jahan Maria", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC025", name: "Shruti Biswas", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC026", name: "G.M Iftikar Mahbub", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC027", name: "Mohammad Ahsanullah", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC028", name: "Sharmir Kumar Sarda", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC029", name: "Mst Samia Rahman Sajin", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC030", name: "Akash Saha", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC031", name: "Mst Mohosina Jim", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC032", name: "Tahmid Ibn Shahab", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC033", name: "Md Mugtadir Hossain", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC034", name: "Samia Afrin Mithi", dept: "Architecture", faculty: "Faculty of Engineering" },
        { clubId: "24SC035", name: "Md Shoriful Islam", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC036", name: "Abdul Hakim Ujjol", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC037", name: "Rubaid Hasan", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC038", name: "Shek Nipa Jahan", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC039", name: "Farzana Akter", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC040", name: "Sumaiya Akhtar", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC041", name: "Fowjia Ahmed Safa", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC042", name: "Lamima Anzum Zahin", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC043", name: "Nadia Islam", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC044", name: "Fariha Sultana", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC045", name: "Md Khalid Mahmud", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC046", name: "Abida Sultana", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC047", name: "Umme Habiba Sumaya", dept: "Pharmacy", faculty: "Faculty of Life Science" },
        { clubId: "24SC048", name: "Barsha Barai", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC049", name: "Most. Sidratul Muntaha", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC050", name: "Sadia Afrin Borni", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC051", name: "Amrita Chakraborty", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC052", name: "Barsha Bawoali", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC053", name: "Johnnabi Tabassum Sneha", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC054", name: "Mahfuja Rashid Mila", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC055", name: "Mst. Farhana Tasnim", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC056", name: "Mahim Sharmin Mim", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC057", name: "Samia Akter Snigdha", dept: "Botany", faculty: "Faculty of Life Science" },
        { clubId: "24SC058", name: "Sadia Rahman Mim", dept: "Chemistry", faculty: "Faculty of Science" },
        { clubId: "24SC059", name: "Joty Rani", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "24SC060", name: "Mst. Monira", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture" },
        { clubId: "24SC061", name: "Marup Haider", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC062", name: "Tasfiya Nusrat Sinthiya", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC063", name: "Mst. Tasnim Salsabil", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC064", name: "Suvra Paul", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC065", name: "Fabiha Bushra", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC066", name: "Sidratul Muntaha", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC067", name: "Nishita Akter", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC068", name: "Esmita Das", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC069", name: "Mst Farjana Akter", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science" },
        { clubId: "24SC070", name: "Jahid Hsan", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC071", name: "Umme Habiba Maisha", dept: "Civil Engineering", faculty: "Faculty of Engineering" },
        { clubId: "24SC072", name: "Siratul Binte Bashar", dept: "Civil Engineering", faculty: "Faculty of Engineering" },

        // --- Batch 25SC ---
        { clubId: "25SC001", name: "Md. Burhanur Rahman", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine", session: "2022-23" },
        { clubId: "25SC002", name: "Tanjina Akter Trisha", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine", session: "2022-23" },
        { clubId: "25SC003", name: "Md. Abu Jubaer", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC004", name: "Md. Nazmul Hossain Noman", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine", session: "2022-23" },
        { clubId: "25SC005", name: "Shamima Akter", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC006", name: "Md. Tawhidur Rahman", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC007", name: "Md. Abir Hasan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC008", name: "Nilanjoly Ayshi", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC009", name: "Emtiaz Ahmed", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC010", name: "Md. Arman Hossain", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC011", name: "Md. Esanur Islam Eshan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC012", name: "Rafiul Bari Shanchay", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC013", name: "Sumaiya Jahan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC014", name: "Rony Das", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC015", name: "Ilma Rahman", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC016", name: "Syeda Zinta Tajnin", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC017", name: "Hafsa Moni", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC018", name: "Umme Habiba Binte Ashraf", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC019", name: "Mohesha Missal Worthy", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC020", name: "Tamanna Akter", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC021", name: "Md. Mustakim Ahmed", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC022", name: "Moutithi Majumder Sumi", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC023", name: "Gourongga Chandra Roy", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC024", name: "Tanvir Islam Khan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC025", name: "Mst. Efat Jahan Esty", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC026", name: "Rafia Sultana Usha", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC027", name: "Annasha Chakraborty Puza", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC028", name: "Azizur Nahar", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2021-22" },
        { clubId: "25SC029", name: "Md. Sahid-Un-Nobi", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2020-21" },
        { clubId: "25SC030", name: "Md. Salman Far", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC031", name: "Sumaiya Tuj Johora", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2020-21" },
        { clubId: "25SC032", name: "Snigdha Roy Moni", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC033", name: "Chandra Shaha", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC034", name: "Toufiq Hasan", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC035", name: "Zobaida Amrin", dept: "Mathematics", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC036", name: "Mst. Luna Parvin", dept: "Psychology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC037", name: "Arpita Shingha", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC038", name: "Mrinmoy Kumar Dey", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC040", name: "Ayon Mallick", dept: "Agriculture", faculty: "Faculty of Agriculture", session: "2021-22" },
        { clubId: "25SC041", name: "Ahsan Habib", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC042", name: "Md. Tazrin Hasan Alve", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC043", name: "Jasika Noor", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC045", name: "Rasel Dewan", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC046", name: "Chaity Roy", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2021-22" },
        { clubId: "25SC047", name: "Md. Shawon Pervez", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine", session: "2023-24" },
        { clubId: "25SC048", name: "Abdullah Al Noman", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2021-22" },
        { clubId: "25SC049", name: "Tanmoy Chandra Deb", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC052", name: "Md. Abid Khan", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC054", name: "Md. Alif Abdullah", dept: "Botany", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC056", name: "Quazi Arib Faisal", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC059", name: "Rudra Bairagi", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC060", name: "Md. Tarikul Islam Riyan", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC061", name: "Shihab Sahriar", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC062", name: "Md. Golam Rabbani", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC063", name: "Zaki Shahriar", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC064", name: "Md. Rokonuzzaman Rasu", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC065", name: "Md. Riad Gazi", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC067", name: "Titly Biswas Ritu", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2020-21" },
        { clubId: "25SC068", name: "Sulov Chandro Pal", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC069", name: "Md. Nayan Islam", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC071", name: "Md. Azizul Islam", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC072", name: "Mushfique Anwar Mahi", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC073", name: "Tuly Adhikary", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC074", name: "Madhab Shill", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC075", name: "Tasnia Tabassum", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC076", name: "Ahashanul Kabir", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC077", name: "Sayma Sultana", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC078", name: "Hafsa Hussain Shamonty", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC079", name: "Tanvir Islam", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC080", name: "Nazia Farhat Hasan", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC081", name: "Sanjida Parvin Silvee", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC082", name: "Tahrim Jannat", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC083", name: "Sabiha Shahab", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC084", name: "Mst. Khadeja Akter", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC085", name: "Ishrat Jahan Prity", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC086", name: "Md. Rezwanul Haque Labib", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC087", name: "Naznin Nahar Nuri", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC088", name: "Shawon Mallick", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC090", name: "ATM Toufiqul Aziz", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC091", name: "Irani Yousuf", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC092", name: "Linkon Biswas", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC093", name: "Maliha Jannat Moumita", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC094", name: "Sintiya Khanom", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC095", name: "Marjia Karim Shefa", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC096", name: "Subaita Sarkar Easha", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC097", name: "Ety Saha", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC099", name: "Sharmin Shultana", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC100", name: "Mst. Zarin Akter", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC103", name: "SM Rawnakul Islam", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC122", name: "Nahid Hasan Monna", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2019-20" },
        { clubId: "25SC123", name: "Asim Kumar", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC124", name: "Jannatul Mawa", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC125", name: "Md. Misbah ur Rahman", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC126", name: "Md. Tufael Hassan Tamjid", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC127", name: "Sheikh Rakib Ahmed", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC128", name: "Syeda Safia Newaz", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC129", name: "Mehedi Hasan Linkon", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2020-21" },
        { clubId: "25SC131", name: "Shamim Hasan Rony", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC133", name: "Md. Sagor Ali", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC135", name: "Moumita Biswas Papri", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC138", name: "Mahabub Alam", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC139", name: "Md. Arafath Patwary Piyal", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC140", name: "Surya Kumar Roy", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC141", name: "Susmoy Chandra Das", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC143", name: "Mst. Sayla Islam Shatu", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC144", name: "Md. Saiman Fuad", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC145", name: "Antor Biswas", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC146", name: "Humaya Nadia Chayan", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC147", name: "Mony Akther", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC148", name: "Mehedi Hasan", dept: "Statistics", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC149", name: "Md. Rasel Mizi", dept: "Statistics", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC151", name: "Raisa Khan", dept: "Botany", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC152", name: "Jarin Akter Juthi", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC153", name: "Onima Akter", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC154", name: "Sanjida Akter", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC155", name: "Umme Erhana Binta Emdad Erin", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC158", name: "Shafin Ahmed", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC159", name: "Shakib Alam", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC160", name: "Farhana Zaman", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC161", name: "Tisha Chakraborty", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC162", name: "Mst. Jasmine Akther", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC163", name: "Tasbiul Bani Tasif", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC164", name: "Israt Jahan Poly", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC165", name: "Sharmin Suriya Mily", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC167", name: "Safat Al Jaber Aronno", dept: "Statistics", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC168", name: "Towhidul Alam", dept: "Statistics", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC172", name: "Sanzida Rahman Sorna", dept: "Statistics", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC175", name: "Puja Paul", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC176", name: "Rabeya Akondo", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC177", name: "Md. Hanjala Shorder", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC178", name: "Abdullah Al Mobin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC181", name: "Uttso Kundu", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC182", name: "Mst. Umme Raihan Dighi Moni", dept: "Animal Science and Veterinary Medicine", faculty: "Faculty of Animal Science and Veterinary Medicine", session: "2022-23" },
        { clubId: "25SC183", name: "Dristy Debnath", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC184", name: "Anamika Dey Ritu", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC186", name: "Israt Jahan Sathi", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC188", name: "Bidhan Kumar Saha", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC189", name: "Chaity Rani Das Kauto", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC190", name: "Disha Datta", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC191", name: "Md. Raichul Islam", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2018-19" },
        { clubId: "25SC192", name: "Anmona Jerin Fiza", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2021-22" },
        { clubId: "25SC198", name: "Poly Sikder", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2020-21" },
        { clubId: "25SC199", name: "Maisa Rahman Rafa", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2020-21" },
        { clubId: "25SC200", name: "Chowdhury Lutfur Nahor Metu", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC201", name: "Md. Mahmudul Hasan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2018-19" },
        { clubId: "25SC210", name: "Md. Hasibur Rahman", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC211", name: "Farham Ishrak Alam", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC212", name: "Mofazzal Hosen", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC213", name: "Bishu Adhikari", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC214", name: "Fahmida Khatun", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC215", name: "Mansheta Kabir Sheona", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC216", name: "Abu Musa", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC217", name: "Simnato Saha", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC218", name: "Jahidul Islam Shayem", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC219", name: "Md. Arafat Hossain", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC220", name: "Ruhul Amin", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC221", name: "Tamal Kanti Mollick", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC223", name: "Manob Mitra Chakma", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC225", name: "Arpita Rani Saha", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC232", name: "Pingky Moni", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC236", name: "Shoriful Islam", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC241", name: "Mujtahid Shahriar Labib", dept: "Architecture", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC242", name: "Md. Sabbir Hossain", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC244", name: "Abed Hossain Talha", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC245", name: "Sadique Muhammad Talha", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC249", name: "Golam Maula", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC250", name: "Farhana Akther Afia", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC251", name: "Sarowar Hossen", dept: "Psychology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC252", name: "Rupa Devnath", dept: "Psychology", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC253", name: "Syed Tahmin Iftakhar Safin", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC254", name: "Asraful Islam", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC255", name: "Arnob Roy", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC256", name: "Anninda Raj Das", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC257", name: "Md. Firoz Ali Ashik", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC258", name: "Samiul Islam Omio", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC259", name: "Shrafat Khan Riad", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC260", name: "Md. Jihad", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC264", name: "KH. Ranak Hasan Ranak", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2022-23" },
        { clubId: "25SC265", name: "Md. Ratul Islam", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC266", name: "Protik Kumar Biswas", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC267", name: "Omar Faruk", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC268", name: "Md. Rakib Babu Sarkar", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2022-23" },
        { clubId: "25SC269", name: "Abdullah Al Nasim", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC270", name: "Md. Sakib Islam", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC271", name: "Abdul Awal Rahi", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2022-23" },
        { clubId: "25SC272", name: "Md. Hafijul Islam", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC273", name: "Mostakim Rahman", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2022-23" },
        { clubId: "25SC274", name: "Tasmin Ara Torna", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC275", name: "Mis. Rumi Akter", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC276", name: "Mst. Mansura Khatun", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC277", name: "Tahiya Tasnim Nijhum", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC278", name: "Mst. Nusrat Jahan Mim", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC279", name: "Faria Yesmin", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2020-21" },
        { clubId: "25SC280", name: "Bushra Akter", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC281", name: "Taiby Jumara Orin", dept: "Architecture", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC300", name: "Etu Barua Joy", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC301", name: "Mohan Uddin", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC302", name: "K.M. Mubash Shir Ahsan", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC303", name: "Prionty Banik", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC304", name: "Aditya Sarker", dept: "Agriculture", faculty: "Faculty of Agriculture", session: "2022-23" },
        { clubId: "25SC305", name: "Saifullah Sarkar", dept: "Agriculture", faculty: "Faculty of Agriculture", session: "2021-22" },
        { clubId: "25SC306", name: "Sumi Khatun", dept: "Botany", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC307", name: "Md. Maidul Islam", dept: "Statistics", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC308", name: "Shariful Islam", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC309", name: "Md. Hasan Mahmud", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC310", name: "Md. Easin Mollah", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2022-23" },
        { clubId: "25SC311", name: "Avik Roy", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC312", name: "Mst. Maria Akter", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC313", name: "Sonia Golder", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC314", name: "Abu Bakkar Siddique", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-24" },
        { clubId: "25SC315", name: "Mymuna Khatun", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC316", name: "Sanjida Akter", dept: "Botany", faculty: "Faculty of Life Science", session: "2022-23" },
        { clubId: "25SC317", name: "Hari Shankor Binda", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC318", name: "Rifat Ahamed Sadib", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },
        { clubId: "25SC319", name: "Anonna Khanom", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2023-24" },
        { clubId: "25SC320", name: "Mohammad Mainur Rahman", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2023-24" },

        // --- Newly Added Batch 25SC Entries (from d.pdf) ---[cite: 2]
        { clubId: "25SC321", name: "MD. Towkin Ahmed Sajol", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC322", name: "Anika Islam", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC323", name: "Md. Alvi Ahamed", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC324", name: "Farhan Zaman Aurko", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC325", name: "Sadhin Roy", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC326", name: "Kazi Mushfiqur Rahman", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC327", name: "Tawhid Rashid Foisal", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC328", name: "Montasir Mahmud", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC329", name: "Srabonti Rani Saha", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC330", name: "Protiksha Adhikary", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC331", name: "Zinnatune Nesa Shanta", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC332", name: "MD. Nasif Quaderi Mahim", dept: "Computer Science and Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC333", name: "Habiba Yesmin Ratri", dept: "Chemistry", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC334", name: "Khadijatul Ferdowsi", dept: "Chemistry", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC335", name: "Sanda Moni", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-2023" },
        { clubId: "25SC336", name: "Md. Naymur Rahman Refat", dept: "Chemistry", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC337", name: "Seyam Mredha", dept: "Chemistry", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC338", name: "Nusrat Jahan", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-2023" },
        { clubId: "25SC339", name: "Md. Shariful Islam", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-2024" },
        { clubId: "25SC340", name: "Md. Rabin Hossain", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2023-2024" },
        { clubId: "25SC341", name: "Hossain Ahmad Fardin", dept: "Chemistry", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC342", name: "Fatema Tuz Johurra", dept: "Chemistry", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC343", name: "Muntasir Islam", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC344", name: "Rabiul Islam", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC345", name: "Md. Ashik Iqbal", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC346", name: "Mst. Mimea Islam Anny", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2023-2025" },
        { clubId: "25SC347", name: "Md. Siam Hossain", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC348", name: "Md. Abdul Ahad", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC349", name: "Faisal Mahmud Islam", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC350", name: "Md. Refat Sonden", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC351", name: "Md. Masum Billah", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC352", name: "Most Ramisha Anjum", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC353", name: "Md. Rejaul Karim", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC354", name: "Md. Tahmid Hasan Siam", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC355", name: "Barnita Sarkar Athay", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC356", name: "Tiasa Tinni Puja", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC357", name: "Karisha Dewan", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC358", name: "Mst. Khalada Farrdowsy", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC359", name: "Punota Anika", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC360", name: "Arman Ahmed Rifat", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC361", name: "Md. Khandoker Alim", dept: "Chemistry", faculty: "Faculty of Science", session: "2023-2024" },
        { clubId: "25SC362", name: "Sujon Kumar Paul", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2021-2022" },
        { clubId: "25SC363", name: "Rakib Shahariare", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC364", name: "Md. Toufik Ahmed", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC365", name: "Mubashir Ahammed", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC366", name: "Debashish Halder", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC367", name: "Nur Mohammod", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2021-2022" },
        { clubId: "25SC368", name: "Arpa Datta", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC369", name: "Md. Shoayeb Ahammed", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC370", name: "Md. Mahedi Hassan", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC371", name: "Anando Paul", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC372", name: "S.M. Abdus Sobur", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC373", name: "Joy Sarkan", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC374", name: "Tonmoy Sanker", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC375", name: "Rama Chakraborily Tinne", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC376", name: "Mst. Mysha Akter", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC377", name: "Mst. Asma Khatun", dept: "History", faculty: "Faculty of Arts and Social Science", session: "2024-2025" },
        { clubId: "25SC378", name: "Soumitra Biswas", dept: "Civil Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC379", name: "Jannatul Afrin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2021-2022" },
        { clubId: "25SC380", name: "Fairuj Israt Arin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC381", name: "Osama Been Oufe", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC382", name: "Arfhia Azrin Momita", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC383", name: "Aishwarya Roy", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC384", name: "Md. Riad Mridha", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC385", name: "Shuvo Pas", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC386", name: "Mst. Sadiya Hoque Mou", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC387", name: "Md. Khairul Habib Rohan", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC388", name: "Hriday Halder", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC389", name: "Md. Nishad Hasan Bhuiyan", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC390", name: "Swarna Halder", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC391", name: "Trisha Rani Mondol", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC392", name: "Nusrat E Zahan Nishat", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC393", name: "Nazmus Sakib", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC394", name: "Boishakey Yasmin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC395", name: "Shusmita Mollick Dola", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC396", name: "Monira Yeasmin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC397", name: "Md. Roky Islam", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC398", name: "Tabassum Binte Hannan", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC399", name: "Tahmina Sultana Nahin", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC400", name: "Swarnalata Sarkar Chaity", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-2024" },
        { clubId: "25SC401", name: "Sadiya Khatun", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-2024" },
        { clubId: "25SC402", name: "Mst. Tuhina Khatun", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2023-2024" },
        { clubId: "25SC403", name: "Saad Mohammad", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC404", name: "Fariha Yesmin Evana", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC405", name: "Depa Paul", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC406", name: "Dipankar Talukder", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC407", name: "Md. Samiuzzaman", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC408", name: "Payel Biswas", dept: "Fisheries and Marine Bioscience", faculty: "Faculty of Agriculture", session: "2024-2025" },
        { clubId: "25SC409", name: "Puja Basu", dept: "Botany", faculty: "Faculty of Life Science", session: "2022-2023" },
        { clubId: "25SC410", name: "Shabiha Jamat Ela", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC411", name: "Jubiya Tisha", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC412", name: "Mimfa Mysha", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC413", name: "Mithila Rani Das", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC414", name: "Puja Saha", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC415", name: "Maysha Akter", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC416", name: "Somya Mim", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC417", name: "Nourin Islam", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-24" },
        { clubId: "25SC418", name: "Asif Ahmed", dept: "Psychology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC419", name: "Yasmin Zaman", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC420", name: "Mahbuba Afrin", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC421", name: "Fariha Israt Mashrufa", dept: "Economics", faculty: "Faculty of Arts and Social Science", session: "2024-2025" },
        { clubId: "25SC422", name: "Md. Fahad Nakib Nabil", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC423", name: "Ariyan Rana Snigdho", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC424", name: "Shahdin Reza Ferdous", dept: "Electrical and Electronic Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC425", name: "Md. Shakib", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC426", name: "Sadia Samme", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC427", name: "Mst Hazera khatun", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC428", name: "Homayra Nur Tanha", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC429", name: "Mst. Khadija Tull Kubra Oishe", dept: "Chemistry", faculty: "Faculty of Science", session: "2021-2022" },
        { clubId: "25SC430", name: "Md khalid Hossain", dept: "Chemistry", faculty: "Faculty of Science", session: "2021-2022" },
        { clubId: "25SC431", name: "Sayma Sultana Sojoni", dept: "Psychology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC432", name: "Nur Ajam Tasnim", dept: "History", faculty: "Faculty of Arts and Social Science", session: "2023-2024" },
        { clubId: "25SC433", name: "MST. Eshita Khatun", dept: "Public Administration", faculty: "Faculty of Arts and Social Science", session: "2024-2025" },
        { clubId: "25SC434", name: "Raton Baroi", dept: "English", faculty: "Faculty of Arts and Social Science", session: "2023-2024" },
        { clubId: "25SC435", name: "Mst Juthe khatun", dept: "Public Administration", faculty: "Faculty of Arts and Social Science", session: "2024-2025" },
        { clubId: "25SC436", name: "Jakaria Ahmed Ratul", dept: "History", faculty: "Faculty of Arts and Social Science", session: "2023-2024" },
        { clubId: "25SC437", name: "Arisha Islam", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC438", name: "Misskatun Farjana Mithila", dept: "Psychology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC439", name: "MD Rafiul Islam", dept: "Agriculture", faculty: "Faculty of Agriculture", session: "2023-2024" },
        { clubId: "25SC440", name: "Tamanna Akter", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2016-2017" },
        { clubId: "25SC441", name: "Sazia Afrin", dept: "N/A", faculty: "N/A", session: "N/A" },
        { clubId: "25SC442", name: "Md Milon Hossen", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC443", name: "Sohan Sheikh", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC444", name: "Shyama Prosad Saha", dept: "Statistics", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC445", name: "Atkia Maisha", dept: "Botany", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC446", name: "Chaity Sarkar", dept: "Food Engineering", faculty: "Faculty of Engineering", session: "2024-2025" },
        { clubId: "25SC447", name: "Tanjila Afrin Sumi", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC448", name: "Rejwana Nasrin Banya", dept: "Statistics", faculty: "Faculty of Science", session: "2023-2024" },
        { clubId: "25SC449", name: "Shanjida Nahar", dept: "Physics", faculty: "Faculty of Science", session: "2021-2022" },
        { clubId: "25SC450", name: "Mojahid Shikder", dept: "Physics", faculty: "Faculty of Science", session: "2021-2022" },
        { clubId: "25SC451", name: "Md. Al Jobaer", dept: "Statistics", faculty: "Faculty of Science", session: "2023-2024" },
        { clubId: "25SC452", name: "Anika Tabassum Tanha", dept: "Statistics", faculty: "Faculty of Science", session: "2023-2024" },
        { clubId: "25SC453", name: "Kumary Prity Pramanik", dept: "Statistics", faculty: "Faculty of Science", session: "2023-2024" },
        { clubId: "25SC454", name: "Nilofa Yeasmin Nipa", dept: "Statistics", faculty: "Faculty of Science", session: "2024-2025" },
        { clubId: "25SC455", name: "Aminur Rashid", dept: "Chemistry", faculty: "Faculty of Science", session: "2022-2023" },
        { clubId: "25SC456", name: "Promi Biswas", dept: "Biotechnology and Genetic Engineering", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC457", name: "Redwan molla", dept: "Pharmacy", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC458", name: "Md. Samiul Islam", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2023-2024" },
        { clubId: "25SC459", name: "S.M. Abul Basher Sajol", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2023-2024" },
        { clubId: "25SC460", name: "Sagar Ahamed", dept: "Applied Chemistry and Chemical Engineering", faculty: "Faculty of Engineering", session: "2023-2024" },
        { clubId: "25SC461", name: "Md. Khalid Hasan Rifat", dept: "Environmental Science and Disaster Management", faculty: "Faculty of Science", session: "2021-2022" },
        { clubId: "25SC462", name: "Joynal Abadin Niloy", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC463", name: "Jannatul Adon", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC464", name: "Nazma Khatun", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC465", name: "Tanjila Afrin Sumi", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC466", name: "Fariha Tasnim Lubna", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC467", name: "MD. Mursad Hasan", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC468", name: "Tasnurjahan Lumi", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC469", name: "Mosharof Hossen", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC470", name: "Abidur Rahman Himel", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC471", name: "Md. Hasnain Ratul", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC472", name: "Sarmin Akter Mim", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC473", name: "Sadia Sultana Joti", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC474", name: "Afia Neshat Jui", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC475", name: "Minhazul Islam Rifat", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC476", name: "Md. Hamidur Rahman Rakib", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC477", name: "Nusrat Zahan Prova", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2023-2024" },
        { clubId: "25SC478", name: "Fahad Nakib Nabil", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC479", name: "Hossain Mohammad Afradh", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" },
        { clubId: "25SC480", name: "Afia Neshat Jui", dept: "Biochemistry and Molecular Biology", faculty: "Faculty of Life Science", session: "2024-2025" }
    ];

    // Populate missing session values across the dataset dynamically
    const sampleMembers = rawMembers.map(member => ({
        ...member,
        session: member.session || calculateSession(member.clubId)
    }));

    if (searchForm && searchInput) {
        searchForm.addEventListener('submit', (e) => {
            e.preventDefault();
            const query = searchInput.value.trim().toLowerCase();

            if (!query) return;

            // Filter all records based on user search query
            const matches = sampleMembers.filter(m =>
                (m.name && m.name.toLowerCase().includes(query)) ||
                (m.clubId && m.clubId.toLowerCase().includes(query)) ||
                (m.dept && m.dept.toLowerCase().includes(query)) ||
                (m.faculty && m.faculty.toLowerCase().includes(query)) ||
                (m.session && m.session.toLowerCase().includes(query))
            );

            // Clear previous results
            resultsContainer.innerHTML = '';

            if (matches.length > 0) {
                notFoundBox.style.display = 'none';

                // Display centered "Record Found" header
                const label = matches.length === 1 ? 'Record Found' : 'Records Found';
                resultCountBox.textContent = `${label}: ${matches.length}`;
                resultCountBox.style.display = 'block';

                // Render each matching result card
                matches.forEach(m => {
                    const card = document.createElement('div');
                    card.className = 'interactive-qa-card';
                    card.style.textAlign = 'left';

                    let rowsHtml = '';
                    if (m.clubId) {
                        rowsHtml += `
                            <div style="display: flex; justify-content: space-between; border-bottom: 1px dashed rgba(32, 58, 67, 0.12); padding-bottom: 6px;">
                                <span>Club ID:</span>
                                <strong>${m.clubId}</strong>
                            </div>`;
                    }
                    if (m.dept) {
                        rowsHtml += `
                            <div style="display: flex; justify-content: space-between; border-bottom: 1px dashed rgba(32, 58, 67, 0.12); padding-bottom: 6px;">
                                <span>Department:</span>
                                <strong>${m.dept}</strong>
                            </div>`;
                    }
                    if (m.faculty) {
                        rowsHtml += `
                            <div style="display: flex; justify-content: space-between; border-bottom: 1px dashed rgba(32, 58, 67, 0.12); padding-bottom: 6px;">
                                <span>Faculty:</span>
                                <strong>${m.faculty}</strong>
                            </div>`;
                    }

                    rowsHtml += `
                        <div style="display: flex; justify-content: space-between;">
                            <span>Session:</span>
                            <strong>${m.session || 'N/A'}</strong>
                        </div>`;

                    card.innerHTML = `
                        <div style="border-bottom: 1px solid rgba(255, 255, 255, 0.1); padding-bottom: 12px; margin-bottom: 15px;">
                            <h3 style="margin: 0; font-size: 1.3rem; color: var(--accent-color);">${m.name || 'Unnamed Member'}</h3>
                        </div>
                        <div style="display: flex; flex-direction: column; gap: 10px; font-size: 0.95rem;">
                            ${rowsHtml}
                        </div>
                    `;

                    resultsContainer.appendChild(card);
                });
            } else {
                resultCountBox.style.display = 'none';
                notFoundBox.style.display = 'block';
            }
        });
    }
});